### ISSUE TITLE
update http://lue3d.org/docs/#getting-started ZBlend plugin link

### ISSUE THREAD

**Issue by 0joshuaolson1** [luboslenco/luboslenco_web#1]
In 3., `http://zblend.org/plugin/zblend.py` should be `http://lue3d.org/plugin/zblend.py` or `https://github.com/luboslenco/lue_blender/blob/master/lue.py`.

**Comment by luboslenco** [comment]
Hello,

ZBlend is being transformed into Lue, which will not depend on Blender. Therefore the docs are currently outdated, will note that up on the site to prevent confusion.
